Implement crit script and tests
HydrologicEngineeringCenter/cwms-python pull request #82
Opened 2024-08-23 18:49 UTC by tlelv

• Adds the critscript into the timeseries directory.
• Adds tests to the critscript in the tests directory
• Adds a JSON for crittesting in the resources directory
• Adds Update_timeseries_groups and timeseries_group_df_to_json to timerseries directory

Passes Poetry tests

2024-08-27 12:56 UTC, Enovotny commented on cwms/timeseries/timeseries.py
> +def update_timeseries_groups(
this should be taking in the json as well.  there should be a parameters data that would include the json used to update the time series group

2024-08-27 12:57 UTC, Enovotny commented on cwms/timeseries/timeseries.py
> +    group_id: str,
the category_id should be passed in as well.  right now you have it defaulting to "data acquisition" but this should be a parameter in the function

2024-08-27 13:00 UTC, Enovotny commented on cwms/timeseries/timeseries.py
> +    required_columns = ["office-id", "ts-id", "alias", "ts-code", "attribute"]
ts-id and office-id should be the only required columns i the dataframe.  for your purpose you will also be passing in alias, but that isn't required in this function.  you should check if it is present in the dataframe and if not create a column and set it to None.  if attribute is not present set it to 0 and is ts-code is not present just don't include it in the json output.  it isn't needed.

2024-08-27 13:03 UTC, Enovotny commented on cwms/timeseries/timeseries.py
> +    for _, row in data.iterrows():
you likely don't need to loop though this.  you could probably use the data.values.tolist() function and it will take care of it.

2024-08-27 13:10 UTC, Enovotny commented on cwms/timeseries/critscript.py
> +    def timeseries_group_df_to_json(data: pd.DataFrame, group_id: str) -> json:
remove this function and replace with call to function you created in timeseries.py

2024-08-27 13:10 UTC, Enovotny commented on cwms/timeseries/critscript.py
> +def crit_script(file_path, office_id, group_id):
remove this function and replace with function you created in timeseries.py

2024-08-27 22:35 UTC, tlelv commented on cwms/timeseries/timeseries.py
> +def update_timeseries_groups(
For the JSON, I can pass is through but it will no longer match what is on the SWGR page. Is that okay?

2024-08-28 12:27 UTC, Enovotny commented on cwms/timeseries/timeseries.py
> +def update_timeseries_groups(
I does require the json. if you look at the patch function in order to run it you need to fill in the json show in this image.  when you hit try it out then it opens and you have to fill it in before you execute.  It is like that for all post/patch functions.  that way the patch knows what to update it with it is all held in the json that is passed in.
![image](https://github.com/user-attachments/assets/39ae09a5-a1f7-41ab-b373-49fc707f6080)

2024-09-07 15:25 UTC, Enovotny requested changes

2024-09-07 15:25 UTC, Enovotny commented on cwms/timeseries/critscript.py
> +json_dict = crit_script("CEMVP_GOES.crit", "CWMS", "Data Acquisition")
you have CWMVP_GOES.crit hard coded in.  this is why your tests are erroring right now.

2024-09-07 15:25 UTC, Enovotny commented on tests/timeseries/timeseries_test.py
> +def test_timeseries_group_df_to_json_and_update_timeseries_groups(sample_dataframe):
test should be singular and testing one component.  So you should have a test for the update time series group.  as well as a seperate test for timeseries group to json.

2024-09-07 15:25 UTC, Enovotny commented on cwms/timeseries/critscript.py
> +                            "Alias": alias + " " + alias2,
I just storing a timeseries into a timeseries group and the deliminator can't be a space.  That won't save into the alias field.  use a : instead here.  alias + ":" + alias2

also need the case if they don't have match.group(3).  they might just have alias and timeseries_id.   could set alias = match.group(1).strip() then if len(match) = 3 alias = alias + ":" + match.group(3).strip() or something like that.

2024-12-06 00:51 UTC, closed without merging