Added gate changes support with associated tests
HydrologicEngineeringCenter/cwms-python pull request #92
Opened 2024-09-25 22:23 UTC by zack-rma

Added gate changes support with associated test cases.

2024-10-01 20:51 UTC, Enovotny requested changes
please add gate_changes to _init file

2024-10-11 17:47 UTC, Enovotny approved these changes

2024-10-23 16:47 UTC, Enovotny approved these changes

2024-10-24 17:30 UTC, adamkorynta commented on cwms/locations/gate_changes.py
> +    page_size: integer, optional
This API doc should borrow language similar to what is on CDA about moving the start date forward to get the next page of data.

2024-10-24 17:32 UTC, adamkorynta commented on cwms/locations/gate_changes.py
> +          "discharge-computation-type": {
Is the type itself stored, or just the display value?

2024-10-24 17:38 UTC, adamkorynta requested changes
some minor comments

2024-10-25 16:42 UTC, zack-rma commented on cwms/locations/gate_changes.py
> +    page_size: integer, optional
Updated doc with language from CDA controller

2024-10-25 21:12 UTC, adamkorynta approved these changes

2024-10-25 21:13 UTC, merged